hu_web/hu_browser/urls.py
from django.conf.urls import url
from hu_browser import views

app_name = 'hu_browser'

urlpatterns = [
    url('^$', views.home, name='home'),
    url('^about/$', views.about, name='about'),
    url('^orgs/$', views.orgs, name='orgs'),
    url('^forum/$', views.forum, name='forum'),
]

hu_web/hu_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('hu_browser.urls')),
    url(r'^toolkits/', include('ghu_toolkits.urls')),
    url(r'^admin/', admin.site.urls),
]

hu_web/uh_browser/urls.py
from django.conf.urls import url
from uh_browser import views

app_name = 'uh_browser'

urlpatterns = [
    url('^$', views.home, name='home'),
    url('^about/$', views.about, name='about'),
    url('^orgs/$', views.orgs, name='orgs'),
    url('^forum/$', views.forum, name='forum'),
]

hu_web/uh_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('uh_browser.urls')),
    url(r'^admin/', admin.site.urls),
]

hu_web/hu_browser/views.py
from django.shortcuts import render
# XXX Remove these when models are finished
from collections import namedtuple
Org = namedtuple('Org', ['name', 'loc', 'categs'])
Categ = namedtuple('Categ', ['name'])
# XXX Put these in a fixture instead of hard-coding them
categs = [
    Categ('community'),
    Categ('education'),
    Categ('general'),
    Categ('health'),
    Categ('seniors'),
    Categ('women'),
    Categ('youth'),
]

def home(request):
    return render(request, 'hu_browser/home.html', {})

def about(request):
    return render(request, 'hu_browser/about.html', {})

def orgs(request):
    # XXX Remove this when models are finished

    examples = [
        Org('IXGEN, Inc.', 'Lithonia, GA, United States', [Categ('community'), Categ('youth')]),
        Org('Clean Water Kenya', 'Ligonier, PA, United States', [Categ('health')]),
        Org('Global Paint for Charity', 'Atlanta, GA, United States', [Categ('general')]),
    ]
    fluff = [Org('An Organization', 'Atlanta, GA, United States', categs)]*32

    ctx = {
        'results': fluff + examples + fluff,
    }

    return render(request, 'hu_browser/orgs.html', ctx)

def forum(request):
    # XXX Remove this when models are finished

    ctx = {
        'categs': categs,
    }

    return render(request, 'hu_browser/forum.html', ctx)

hu_web/uh_browser/views.py
from django.shortcuts import render
# XXX Remove these when models are finished
from collections import namedtuple
Org = namedtuple('Org', ['name', 'loc', 'categs'])
Categ = namedtuple('Categ', ['name'])
# XXX Put these in a fixture instead of hard-coding them
categs = [
    Categ('community'),
    Categ('education'),
    Categ('general'),
    Categ('health'),
    Categ('seniors'),
    Categ('women'),
    Categ('youth'),
]

def home(request):
    return render(request, 'uh_browser/home.html', {})

def about(request):
    return render(request, 'uh_browser/about.html', {})

def orgs(request):
    # XXX Remove this when models are finished

    ctx = {
        'results': [Org('An Organization', 'Atlanta, GA, United States', categs)]*64,
    }

    return render(request, 'uh_browser/orgs.html', ctx)

def forum(request):
    # XXX Remove this when models are finished

    ctx = {
        'categs': categs,
    }

    return render(request, 'uh_browser/forum.html', ctx)

hu_web/hu_browser/templates/hu_browser/about.html
{% extends 'hu_browser/layout.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <h1>About Humanitarians United</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at aliquam odio. Pellentesque sed pharetra eros, vel rhoncus tortor. Vivamus hendrerit purus eget sem finibus, et congue lorem hendrerit. Praesent bibendum dui in ligula tincidunt ullamcorper. Quisque in pretium lacus, nec vehicula metus. Donec dui est, feugiat ac varius sed, mattis eget turpis. Nunc sit amet ultrices turpis. Vivamus porttitor aliquam odio. Fusce eleifend metus risus, sed vehicula enim congue quis. Aenean aliquet porta placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In et lorem non diam semper tincidunt. In ultricies feugiat aliquam. Aliquam erat volutpat. Donec gravida dui eget nibh suscipit, sed lobortis erat lacinia.</p>
    <p>Aenean porttitor arcu et sem congue imperdiet at eu lacus. Curabitur auctor sapien eros, id malesuada justo consectetur eleifend. Nullam in dolor placerat, pulvinar metus at, malesuada libero. Phasellus posuere tellus nibh, at posuere ligula cursus ac. Nulla lectus lectus, auctor et diam nec, fermentum fermentum lectus. Nulla tempor interdum mi. Nullam quis orci et neque auctor egestas. Duis interdum nunc eget ligula feugiat, vel accumsan neque molestie. Sed rutrum rutrum nibh at iaculis. Ut consequat nisl facilisis, convallis ligula sed, mattis sapien. Etiam egestas sodales dui, a gravida justo consequat in. Quisque sapien quam, placerat eget lobortis id, pellentesque nec mauris. Ut ut neque id est placerat pellentesque at vel nulla.</p>
    <p>Vivamus nulla ligula, gravida ac ipsum vel, dignissim dapibus ipsum. Sed ultrices ut nisi vulputate faucibus. Cras fringilla, dui id mollis interdum, dolor odio pharetra mauris, id bibendum felis sem at mi. Sed a massa sed eros vulputate lacinia. Pellentesque sagittis ex eu fermentum vulputate. Donec volutpat ante commodo libero gravida dictum. Aenean malesuada bibendum libero accumsan vestibulum. Nulla eu tempus tortor, in cursus mi. Nulla sit amet odio ut purus faucibus vehicula in rhoncus nisl.</p>
    <p>Quisque molestie vel justo eu gravida. Cras finibus sapien a tortor feugiat rhoncus. Quisque ut porta odio. Sed at nunc sem. Nulla fringilla dignissim ligula sed aliquet. Ut sed elementum augue. Donec sit amet lectus ut sapien rutrum sagittis in ac risus. Suspendisse rutrum vehicula tortor et euismod. Praesent consectetur diam eget varius consequat. Quisque eu augue quis metus pretium sodales. Nunc ultrices rhoncus felis nec rutrum. Ut interdum ex malesuada orci tempus, sed ornare est lobortis.</p>
    <p>Morbi ac arcu ornare, faucibus libero nec, eleifend magna. Nam erat quam, ullamcorper a leo sit amet, semper vulputate massa. Integer viverra felis at interdum gravida. Phasellus commodo ante sed dignissim lacinia. Pellentesque tincidunt tortor odio, aliquet dictum diam pellentesque vel. Nulla vel turpis vehicula, iaculis nunc quis, suscipit massa. Etiam egestas nec augue non accumsan. Nulla a sagittis diam, a condimentum nulla. Duis nec sagittis dolor.</p>
    <p>Nam finibus elit eget ante rutrum pulvinar. Curabitur ultricies vel arcu sed scelerisque. Nunc commodo consectetur mi, sed euismod augue hendrerit a. Nulla tincidunt odio vitae tellus convallis, sit amet vestibulum libero egestas. Cras accumsan nisl quis elit ultrices, a sollicitudin sem tincidunt. In hac habitasse platea dictumst. Mauris ac malesuada neque. Fusce augue nulla, ultrices quis ornare quis, volutpat ut mi. Vestibulum tempus tincidunt ultrices. Praesent at lacinia dolor. Vivamus tincidunt, tellus ut aliquet facilisis, augue diam suscipit odio, eget dictum lacus magna ut orci. Nulla facilisi. Nunc at pulvinar ante. Praesent convallis tempor pellentesque. In mattis ut nunc eu blandit. Aenean dictum blandit condimentum.</p>
    <p>Vivamus eros tortor, imperdiet eu justo eget, maximus eleifend eros. Etiam luctus vel ante sollicitudin volutpat. Cras quam neque, pellentesque at ex condimentum, finibus sagittis odio. Suspendisse mauris tellus, finibus sit amet faucibus sed, tincidunt quis augue. Cras in commodo mauris, at egestas justo. Phasellus tincidunt, tellus quis malesuada consequat, diam tortor cursus libero, in lacinia lectus eros at ex. Mauris viverra et enim nec pretium. Duis sit amet volutpat nisi.</p>
    <p>Phasellus tincidunt efficitur vestibulum. Mauris condimentum lorem ut dui pellentesque tincidunt. Nulla tristique tincidunt lorem vitae vehicula. Donec ac ultrices ligula. Donec porta mattis elit ut convallis. Nulla facilisi. Mauris sollicitudin ex ipsum, sed ultrices tortor molestie aliquet. Nulla a gravida augue, ac mollis odio. Morbi iaculis facilisis est, id vestibulum massa malesuada sed. Proin hendrerit lorem eget nunc porta, sit amet dictum eros gravida. Ut varius, eros sit amet posuere dapibus, risus turpis venenatis est, eu tristique ipsum felis ut arcu. Phasellus tempor libero libero, at dignissim urna suscipit vel. Aenean luctus lacus arcu, id ornare tortor tincidunt a. Etiam at iaculis tellus, eget faucibus est. Sed cursus sit amet tortor vitae congue. Cras sodales est quis neque gravida ullamcorper.</p>
    <p>Nam molestie et mauris sit amet aliquam. Aenean porttitor magna at nulla euismod, et consequat felis tempor. In dictum lectus vel velit ullamcorper placerat. Quisque iaculis nunc in nisi tincidunt tempor. Ut eget lacinia lectus. Suspendisse eu imperdiet orci, et condimentum purus. Phasellus efficitur, nisi non gravida ullamcorper, ligula odio volutpat purus, eu lacinia mi quam eget felis. Etiam varius est egestas orci dapibus, vitae convallis ligula finibus. Nunc id fermentum arcu. Aenean purus tellus, congue quis lacus eget, mollis venenatis libero. Aenean maximus tincidunt convallis. Etiam placerat neque at felis venenatis pharetra. Morbi non libero quis lectus sollicitudin sagittis in vitae lorem. Nam vulputate tortor tristique, fermentum mauris efficitur, fringilla metus.</p>
    <p>Aenean vel dui ipsum. Cras laoreet, augue nec pulvinar tincidunt, metus nisl porttitor neque, sed efficitur libero erat ac lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam tristique dolor sit amet est pulvinar, non maximus lorem fringilla. Duis et ex non magna ultricies ullamcorper id eu nunc. Pellentesque cursus mi vel nunc ultrices malesuada. Sed porttitor ex ante, quis suscipit urna facilisis ac. Aenean eros nibh, lobortis sed molestie nec, placerat eu justo. Nunc auctor, nulla ut vehicula tincidunt, lectus lacus hendrerit lectus, vel laoreet risus mauris in nibh. Phasellus condimentum et augue at fringilla. Mauris a felis ut turpis luctus porttitor nec ac metus. Quisque molestie massa vel leo scelerisque mattis. Quisque lobortis mi magna, non ultricies enim mollis sit amet. Suspendisse eu nisl odio. Sed sagittis ut nunc fermentum feugiat.</p>
    <p>Donec a mauris id ante malesuada placerat. Nullam libero nulla, gravida ut diam vel, vulputate volutpat erat. Nunc vulputate enim neque, et elementum neque placerat at. Praesent ac ex molestie enim tempor euismod vitae nec sem. Nam tempor justo eget sapien finibus, ac dignissim velit imperdiet. Vivamus mollis gravida sapien et vehicula. Integer convallis tortor sed nisi dictum, vel molestie ipsum porttitor.</p>
    <p>Phasellus commodo laoreet turpis porta scelerisque. Curabitur et mattis urna, eget mollis velit. Nunc eget lacus at odio pellentesque pellentesque a non turpis. Nulla nec dui a risus auctor scelerisque sed eget nisi. Sed auctor egestas lorem, at bibendum nibh. Curabitur feugiat posuere est a aliquam. Integer eu auctor ex. Duis id risus at sapien dignissim rhoncus eu et elit. Duis a elit a felis congue tempus vel id leo. Proin malesuada sapien eros. Fusce non venenatis metus. Morbi id eleifend nulla. Integer a est nec sapien egestas consectetur. Morbi porttitor nunc erat.</p>
    <p>Aenean et nisl ut augue euismod tempor. Maecenas molestie, sem quis porttitor cursus, ipsum quam hendrerit magna, et suscipit sem ligula ut augue. Suspendisse blandit fermentum dui non imperdiet. Mauris eu ipsum odio. Vestibulum egestas convallis semper. Fusce augue sapien, fermentum id feugiat non, pellentesque id ligula. Proin sed odio est. Nam volutpat sapien ut aliquam volutpat. Morbi pellentesque felis blandit egestas finibus.</p>
    <p>Pellentesque laoreet euismod massa a pretium. Integer ut nulla venenatis, luctus magna vel, ornare felis. Nam blandit eros id pulvinar ultricies. Aliquam eu malesuada dolor. Aliquam molestie tortor at turpis vehicula, et malesuada sapien suscipit. Nulla quis hendrerit lacus. Integer eleifend posuere lorem, ac vulputate sem malesuada at</p>
    <p>Maecenas lacinia ligula quis sapien blandit dignissim. Nam ac feugiat magna, sit amet dictum tortor. Donec euismod metus et orci sollicitudin rutrum. Quisque sed metus sit amet purus aliquet tincidunt eu eu sapien. Integer eget sem in metus porttitor pharetra. Curabitur purus metus, dapibus a rhoncus ut, tincidunt ut nibh. Praesent facilisis metus ac dui feugiat, ac volutpat ante laoreet. Donec elementum nec ante ac scelerisque. Suspendisse vel interdum diam, sit amet egestas nibh. Duis egestas nibh sit amet lacus aliquet, vel vehicula ex ultricies.</p>
{% endblock %}

hu_web/hu_browser/templates/hu_browser/forum.html
{% extends 'hu_browser/layout.html' %}
{% load static %}
{% block styles %}
    <link href="{% static "/hu_browser/css/forum.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}Forum{% endblock %}
{% block content %}
    <div id="categs">
        {# Remove whitespace-only elements between categ-entries #}
        {% spaceless %}
        {% for categ in categs %}
            {% if forloop.counter0|divisibleby:3 %}
                {# In interior rows, close <div class="categs-row"> opened below in a previous iteration #}
                {% if not forloop.first %}
                    </div>
                {% endif %}
                <div class="categs-row">
            {% endif %}
            {% with "/hu_browser/img/categ-"|add:categ.name|add:".png" as image_url %}
                <a class="categs-entry" href="#">
                    <img src="{% static image_url %}">
                    <div class="categs-name">{{ categ.name|title }}</div>
                </a>
            {% endwith %}
            {# On the last row, close <div class="categs-row"> opened above #}
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
        {% endspaceless %}
    </div>
{% endblock %}

hu_web/hu_browser/templates/hu_browser/layout.html
{% load static %}<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} — Humanitarians United</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static "/hu_browser/css/style.css" %}" rel="stylesheet">
        <link href="{% static "/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
        {% block styles %}{% endblock %}
    </head>
    <body>
        <div id="authbar">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#login-modal">Login</button>
            <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#register-modal">Sign up</button>
        </div>
        <header>
            <a id="logo" href="{% url 'hu_browser:home' %}">Humanitarians United</a>
            <nav>
                <ul>
                    <li><a href="{% url 'hu_browser:about' %}">About</a></li><!--
                 --><li><a href="{% url 'hu_browser:orgs' %}">Organizations</a></li><!--
                 --><li><a href="{% url 'hu_browser:forum' %}">Forum</a></li>
                </ul>
            </nav>
        </header>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">&copy; 2017 Humanitarians United &mdash; <a href="https://github.com/humanitarians-united/hu">Source code</a></div>

        {# Account modals #}
        <div id="login-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Login</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="login-modal-username">Username</label>
                                <input type="text" class="form-control" id="login-modal-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="login-modal-password">Password</label>
                                <input type="password" class="form-control" id="login-modal-password" placeholder="Password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Login</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="register-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Register</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="register-modal-username">Username</label>
                                <input type="text" class="form-control" id="register-modal-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="register-modal-email">Email</label>
                                <input type="email" class="form-control" id="register-modal-email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <label for="register-modal-password">Password</label>
                                <input type="password" class="form-control" id="register-modal-password" placeholder="Password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Register</button>
                    </div>
                </div>
            </div>
        </div>

        {# Scripts #}
        <script src="{% static "/jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "/bootstrap/dist/js/bootstrap.min.js" %}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

hu_web/hu_browser/templates/hu_browser/orgs.html
{% extends 'hu_browser/layout.html' %}
{% load static %}
{% block styles %}
    <link href="{% static "/hu_browser/css/orgs.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}Organizations{% endblock %}
{% block scripts %}
    <script src="{% static "/hu_browser/js/orgs.js" %}"></script>
{% endblock %}
{% block content %}
    <div id="container" class="container">
        <div id="search" class="input-group">
            <input id="org-search-field" type="text" class="form-control" placeholder="Search Organizations">
            <span class="input-group-btn">
                <button id="org-search-btn" class="btn btn-primary" type="button"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
        <ul id="results">
            {% for org in results %}
                <li><a href="#">
                    <div class="results-name">{{ org.name }}</div><br>
                    <div class="results-loc">{{ org.loc }}</div>
                    <ul class="results-categs">
                        {% for categ in org.categs %}
                            {% with "/hu_browser/img/categ-"|add:categ.name|add:".png" as image_url %}
                                <li><img title="{{ categ.name|title }}" src="{% static image_url %}"></li>
                            {% endwith %}
                        {% endfor %}
                    </ul>
                </a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

hu_web/uh_browser/templates/uh_browser/forum.html
{% extends 'uh_browser/layout.html' %}
{% load static %}
{% block styles %}
    <link href="{% static "/uh_browser/css/forum.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}Forum{% endblock %}
{% block content %}
    <div id="categs">
        {# Remove whitespace-only elements between categ-entries #}
        {% spaceless %}
        {% for categ in categs %}
            {% if forloop.counter0|divisibleby:3 %}
                {# In interior rows, close <div class="categs-row"> opened below in a previous iteration #}
                {% if not forloop.first %}
                    </div>
                {% endif %}
                <div class="categs-row">
            {% endif %}
            {% with "/uh_browser/img/categ-"|add:categ.name|add:".png" as image_url %}
                <a class="categs-entry" href="#">
                    <img src="{% static image_url %}">
                    <div class="categs-name">{{ categ.name|title }}</div>
                </a>
            {% endwith %}
            {# On the last row, close <div class="categs-row"> opened above #}
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
        {% endspaceless %}
    </div>
{% endblock %}

hu_web/uh_browser/templates/uh_browser/layout.html
{% load static %}<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} — Uniting Humanitarians</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static "/uh_browser/css/style.css" %}" rel="stylesheet">
        <link href="{% static "/uh_browser/bower/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
        {% block styles %}{% endblock %}
    </head>
    <body>
        <div id="authbar">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#login-modal">Login</button>
            <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#register-modal">Sign up</button>
        </div>
        <header>
            <a id="logo" href="{% url 'uh_browser:home' %}">Uniting Humanitarians</a>
            <nav>
                <ul>
                    <li><a href="{% url 'uh_browser:about' %}">About</a></li><!--
                 --><li><a href="{% url 'uh_browser:orgs' %}">Organizations</a></li><!--
                 --><li><a href="{% url 'uh_browser:forum' %}">Forum</a></li>
                </ul>
            </nav>
        </header>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">&copy; 2017 Uniting Humanitarians</div>

        {# Account modals #}
        <div id="login-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Login</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="login-modal-username">Username</label>
                                <input type="text" class="form-control" id="login-modal-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="login-modal-password">Password</label>
                                <input type="password" class="form-control" id="login-modal-password" placeholder="Password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Login</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="register-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Register</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="register-modal-username">Username</label>
                                <input type="text" class="form-control" id="register-modal-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="register-modal-email">Email</label>
                                <input type="email" class="form-control" id="register-modal-email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <label for="register-modal-password">Password</label>
                                <input type="password" class="form-control" id="register-modal-password" placeholder="Password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Register</button>
                    </div>
                </div>
            </div>
        </div>

        {# Scripts #}
        <script src="{% static "/uh_browser/bower/jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "/uh_browser/bower/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    </body>
</html>

hu_web/uh_browser/templates/uh_browser/orgs.html
{% extends 'uh_browser/layout.html' %}
{% load static %}
{% block styles %}
    <link href="{% static "/uh_browser/css/orgs.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}Organizations{% endblock %}
{% block content %}
    <div id="container" class="container">
        <div id="search" class="input-group">
            <input type="text" class="form-control" placeholder="Search Organizations">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
        <ul id="results">
            {% for org in results %}
                <li><a href="#">
                    <div class="results-name">{{ org.name }}</div><br>
                    <div class="results-loc">{{ org.loc }}</div>
                    <ul class="results-categs">
                        {% for categ in org.categs %}
                            {% with "/uh_browser/img/categ-"|add:categ.name|add:".png" as image_url %}
                                <li><img title="{{ categ.name|title }}" src="{% static image_url %}"></li>
                            {% endwith %}
                        {% endfor %}
                    </ul>
                </a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}