ghu_web/ghu_main/urls.py
from django.conf.urls import url
from ghu_main import views
from django.contrib.auth import views as auth_views

app_name = 'ghu_main'

urlpatterns = [
    url(r'^$', views.page, name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/activate/(?P<uid>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^organizations/$', views.organizations, name='organizations'),
    url(r'^toolkits/$', views.toolkits, name='toolkits'),
    url(r'^toolkit/(?P<slug>[a-zA-Z0-9_\-]+)/$', views.toolkit, name='toolkit'),
    url(r'^toolkit/(?P<toolkit_slug>[a-zA-Z0-9_\-]+)/(?P<toolkitpage_slug>[a-zA-Z0-9_\-]+)/$', views.toolkitpage, name='toolkitpage'),
    url(r'^profiles/(?P<slug>.+)/$', views.org_profile, name='profile'),
    url(r'^(?P<slug>.+)/$', views.page, name='page'),
]

ghu_web/ghu_web/urls.py
from django.conf.urls import url, include
from .admin import admin_site

urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'^', include('ghu_main.urls')),
]

ghu_web/ghu_main/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.core.exceptions import ValidationError
from ordered_model.models import OrderedModel
from django.contrib.auth.models import User, Group
from django.conf import settings

# Useful for attempting full-text search on fields
class SearchManager(models.Manager):
    def __init__(self, search_fields):
        super().__init__()
        self.search_fields = search_fields

    def search(self, terms):
        # Return everything for an empty search
        if not terms.strip():
            return self.all()

        # Currently, field__search='foo' (full text search) is supported
        # only on postgres, but fake it on other backends
        if settings.HAS_FULL_TEXT_SEARCH:
            suffix = '__search'
        else:
            suffix = '__icontains'

        query = None
        for search_field in self.search_fields:
            q = Q(**{search_field + suffix: terms})

            if query is None:
                query = q
            else:
                query = query | q

        return self.filter(query)

class NavbarEntry(OrderedModel):
    URL_CHOICES = (('ghu_main:toolkits', 'Toolkits listing'),
                    ('ghu_main:organizations', 'Organizations'))

    label = models.CharField(max_length=256)
    page = models.ForeignKey('Page', on_delete=models.CASCADE, null=True,
                             blank=True)
    url = models.CharField(max_length=256, verbose_name='Special page',
                           choices=URL_CHOICES, blank=True)

    class Meta(OrderedModel.Meta):
        verbose_name = 'Navigation bar entry'
        verbose_name_plural = 'Navigation bar entries'

    def __str__(self):
        return '{}, {}, {}'.format(self.label, self.order, self.page)

    def clean(self):
        if (not self.page and not self.url) or (self.page and self.url):
            raise ValidationError('Must specify either a Page or Special '
                                  'page, but not both')

class Page(models.Model):
    slug = models.SlugField(blank=True, unique=True)
    title = models.CharField(max_length=256)
    contents = models.TextField()
    template = models.ForeignKey('PageTemplate', null=True, blank=True)

    def __str__(self):
        return 'Page "{}": /{}/'.format(self.title, self.slug)

class PageTemplate(models.Model):
    name = models.CharField(max_length=256, verbose_name='User-friendly title')
    template = models.CharField(max_length=256, verbose_name='Template to execute')

    def __str__(self):
        return '{} ({})'.format(self.name, self.template)

class Toolkit(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=256)
    summary = models.TextField()

    def __str__(self):
        return 'Toolkit: {}'.format(self.title)

class ToolkitPage(OrderedModel):
    toolkit = models.ForeignKey(Toolkit, related_name='pages')
    slug = models.SlugField()
    title = models.CharField(max_length=256)
    contents = models.TextField()
    order_with_respect_to = 'toolkit'

    class Meta(OrderedModel.Meta):
        unique_together = (('toolkit', 'slug'),)

    def __str__(self):
        return '{}. Order: {}'.format(self.toolkit, self.order)

class OrgProfile(models.Model):
    slug = models.SlugField(blank=True, unique=True)
    name = models.CharField(max_length=256)
    email = models.EmailField(max_length=254)
    location = models.CharField(max_length=256, null=True)
    phone = models.CharField(max_length=256)
    summary = models.CharField(max_length=256, null=True)
    description = models.TextField()

    objects = SearchManager(('name', 'summary', 'description'))

    def __str__(self):
        return 'OrgProfile: {}, slug: {}'.format(self.name, self.slug)

ghu_web/ghu_main/forms.py
from django import forms
from django.core.exceptions import ValidationError
from ghu_global.models import User
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.password_validation import validate_password

def unused_username(username):
    if User.objects.filter(username=username).count() > 0:
        raise ValidationError('Username {} is already in use.'.format(username))

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=User._meta.get_field('username').max_length,
                               validators=(UnicodeUsernameValidator, unused_username))
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput, validators=(validate_password,))

    def save(self):
        user = User.objects.create_user(username=self.cleaned_data['username'],
                                        email=self.cleaned_data['email'],
                                        password=self.cleaned_data['password'],
                                        is_active=False)

        return user

class SearchForm(forms.Form):
    search_terms = forms.CharField(label = 'Search', max_length = 100, required = False)

ghu_web/ghu_main/views.py
from django.core.exceptions import PermissionDenied
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import redirect, render
from django.http import Http404
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from ghu_global.models import User
from .email import EmailAPI
from .forms import RegisterForm, SearchForm
from .models import Page, NavbarEntry, Toolkit, ToolkitPage, OrgProfile

def page(request, slug=None):
    if slug is None:
        slug = ''

    try:
        page = Page.objects.get(slug=slug)
    except Page.DoesNotExist:
        raise Http404()

    if page.template:
        template = page.template.template
    else:
        template = 'ghu_main/page.html'
    context = {'page': page, 'navbar': NavbarEntry.objects.all()}
    return render(request, template, context)

def organizations(request):
    form = SearchForm(request.GET)
    form.is_valid()
    context = {'organizations': OrgProfile.objects.search(form.cleaned_data['search_terms']),
                'form': form}
    return render(request, 'ghu_main/organizations.html', context)

def toolkits(request):
    context = {'toolkits': Toolkit.objects.all()}
    return render(request, 'ghu_main/toolkits.html', context)

def toolkit(request, slug):
    try:
        toolkit = Toolkit.objects.get(slug=slug)
    except Toolkit.DoesNotExist:
        raise Http404()

    context = {'toolkit': toolkit}
    return render(request, 'ghu_main/toolkit.html', context)

def toolkitpage(request, toolkit_slug, toolkitpage_slug):
    try:
        toolkitpage = ToolkitPage.objects.get(slug=toolkitpage_slug, toolkit__slug=toolkit_slug)
    except ToolkitPage.DoesNotExist:
        raise Http404()

    context = {'toolkitpage': toolkitpage}
    return render(request, 'ghu_main/toolkitpage.html', context)

def org_profile(request, slug):
    try:
        profile = OrgProfile.objects.get(slug=slug)
    except Toolkit.DoesNotExist:
        raise Http404()

    context = {'profiles': profile}
    return render(request, 'ghu_main/org_profile.html', context)

def register(request):
    form = RegisterForm(request.POST if request.method == 'POST' else None)
    ctx = {}

    if request.method == 'POST' and form.is_valid():
        user = form.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        confirm_url = request.build_absolute_uri(reverse('ghu_main:activate', kwargs=dict(token=token, uid=uid)))

        EmailAPI.send_email(subject='Confirm GHU Account',
                            message='Click the following link to confirm your '
                                    'acccount: {}\n\nThanks,\nGHU Staff'
                                    .format(confirm_url),
                            recipients=(user.email,))
    else:
        ctx['form'] = form

    return render(request, 'registration/register.html', ctx)

def activate(request, uid, token):
    """Activate a newly-registered (but inactive) account."""

    uid = urlsafe_base64_decode(uid)
    user = User.objects.get(pk=uid)
    if not user.is_active and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('ghu_main:home')
    else:
        raise PermissionDenied()

ghu_web/ghu_main/templates/ghu_main/base.html
{% extends 'ghu_global/layout.html' %}
{% load static %}
{% block site_name %}Global Humanitarians Unite{% endblock %}
{% block styles %}
    {{ block.super }}
    <link href="{% static "/ghu_main/css/base.css" %}" rel="stylesheet">
{% endblock %}
{% block header %}
    <div id="logo" class="container">
        <a href="{% url 'ghu_main:home' %}">Global Humanitarians Unite</a>
    </div>

    <div class="jumbotron">
      <div id="jumbotron-title" class="title-phrase">
        <p class="lead">- Connecting Humanitarians to Improve the World -</p>
      </div>
    </div>
    <a id="feedback" href="{{ settings.FEEDBACK_FORM_URL }}" target="_blank">Feedback</a>
    {% if user.is_authenticated %}
        <a id="logout" href="{% url 'ghu_main:logout' %}">Log out</a>
    {% else %}
        <a id="login" href="{% url 'ghu_main:login' %}">Log in</a>
        <a id="register" href="{% url 'ghu_main:register' %}">Register</a>
    {% endif %}

    <nav class="navbar navbar-default collapsed">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% for entry in navbar %}
                        <li><a href="{% if entry.page %}{% if entry.page.slug %}{% url 'ghu_main:page' slug=entry.page.slug %}{% else %}{% url 'ghu_main:home' %}{% endif %}{% else %}{% url entry.url %}{% endif %}">{{ entry.label }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/donate.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}Donate{% endblock %}
{% block styles %}
    {{ block.super }}
    <link href="{% static "/ghu_main/css/donate.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div id="container">
        <h1>Donate</h1>
    </div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/org_profile.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}Profiles{% endblock %}
{% block styles %}
    {{ block.super }}
    <link href="{% static "/ghu_main/css/generic-list.css" %}" rel="stylesheet">
    <style>
      p strong:first-child {
          display:inline;
      }
    </style>
{% endblock %}
{% block content %}
    <h1>Profiles</h1>
    <div class="container">
        <p>
          <strong>Name: </strong>{{ profiles.name }}<br />
          <strong>E-mail: </strong>{{ profiles.email }}<br />
          <strong>Location: </strong>{{ profiles.location }}<br />
          <strong>Profiles: </strong>{{ profiles.phone }}<br />
          <strong>Summary: </strong>{{ profiles.summary }}<br />
          <strong>Description: </strong>{{ profiles.description }}<br />
        </p>
    </div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/organizations.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}Organizations{% endblock %}
{% block styles %}
    {{ block.super }}
    <link href="{% static "/ghu_main/css/organizations.css" %}" rel="stylesheet">
    <link href="{% static "/ghu_main/css/generic-list.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1>Organizations</h1>
    <div class="container">
        <form action="" method="get">
            {{ form }}
            <input type="submit" value = "Submit" />
        </form>
        {% for organization in organizations %}
            <p class="list-entry">
                <a id="organization-link" href="{% url 'ghu_main:profile' slug=organization.slug %}">
                    <strong>{{ organization.name}}</strong><br />
                    {{ organization.summary }}
                </a>
            </p>
        {% endfor %}
    </div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/page.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
    <h1 id="page-title">{{ page.title }}</h1>
    <div class="container">{{ page.contents | safe }}</div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/toolkit.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}{{ toolkit.title }}{% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ toolkit.title }}</h1>
        <div id="summary">{{ toolkit.summary }}</div>
        <ol>
            {% for toolkitpage in toolkit.pages.all %}
            <li><a href="{% url 'ghu_main:toolkitpage' toolkit_slug=toolkit.slug toolkitpage_slug=toolkitpage.slug %}">{{ toolkitpage.title }}</a></li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/toolkitpage.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}{{ toolkitpage.title }}{% endblock %}
{% block content %}
    <div class="container">
      <h1>{{ toolkitpage.title }}</h1>
      <div id="contents">{{ toolkitpage.contents | safe }}</div>
    </div>
{% endblock %}

ghu_web/ghu_main/templates/ghu_main/toolkits.html
{% extends 'ghu_main/base.html' %}
{% load static %}
{% block title %}Toolkits{% endblock %}
{% block styles %}
    {{ block.super }}
    <link href="{% static "/ghu_main/css/toolkits.css" %}" rel="stylesheet">
    <link href="{% static "/ghu_main/css/generic-list.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1>Toolkits</h1>
    <div class="container">
        {% for toolkit in toolkits %}
            <p class="list-entry">
                <a id="toolkit-link" href="{% url 'ghu_main:toolkit' slug=toolkit.slug %}">
                    <strong>{{ toolkit.title }}</strong><br />
                    {{ toolkit.summary }}
                </a>
            </p>
        {% endfor %}
    </div>
{% endblock %}